# Generated by Django 4.1.5 on 2023-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='id',
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
