# Generated by Django 4.1.5 on 2023-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_new_id_alter_new_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
